use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
<<<<<<< HEAD
config :sagaBetaV3, SagaBetaV3Web.Endpoint,
=======
config :storyBeta, StoryBetaWeb.Endpoint,
>>>>>>> d56f3c5fa6389bf65331331d54945619585cf187
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
<<<<<<< HEAD
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
=======
# In order to use HTTPS in development, a self-s/code.ex:629: Code.load_file/2
# certificate can be generated by running the fo    (mix) lib/mix/cli.ex:29: Mix.CLI.proceed/1
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 36    (elixir) lib/code.ex:677: Code.require_file/2ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:~/code/mobile-dev/server/storyBeta ᐅ 
>>>>>>> d56f3c5fa6389bf65331331d54945619585cf187
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :storyBeta, StoryBeta.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "storybeta_dev",
  hostname: "localhost",
  pool_size: 10
